# Flutter Analysis Options
# Enhanced static analysis configuration for better code quality
#
# This file is copied to new Flutter projects by flutter-ios-setup
# to enforce consistent coding standards.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style rules
    prefer_single_quotes: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true

    # Documentation
    public_member_api_docs: false  # Set to true for libraries

    # Formatting
    lines_longer_than_80_chars: true

    # Error prevention
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_returning_null_for_void: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    use_build_context_synchronously: true

    # Best practices
    use_key_in_widget_constructors: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    use_rethrow_when_possible: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"

  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    missing_return: error

    # Warnings
    invalid_annotation_target: warning

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
